(define (repl)
  (let loop ()
    (display "> ")
    (let ((input (read)))
      (unless (eof-object? input)
        (let ((result (eval input (interaction-environment))))
          (unless (eq? (if #f #f) result)
            (write result)
            (newline))
          (loop))))))

(define (main args)
  (let ((files (cdr args)))
    (if (null? files)
        (repl)
        (for-each load files))))

(main (command-line))
